# CWTS Data

Comparator dataset

In [14]:
import pandas as pd

import sys
from pathlib import Path

PROJECT_ROOT = Path().resolve().parent
sys.path.append(str(PROJECT_ROOT))

from general.util.banned_words import add_flagged_column

In [23]:
df_comp = pd.read_excel('00_data/banned_data_202602.xlsx', sheet_name='data_not_us_gov')
df_aff = pd.read_excel('00_data/banned_data_202602.xlsx', sheet_name='data_us_gov_affils')

In [41]:
df_aff = pd.read_excel('00_data/banned_data_202602.xlsx', sheet_name='data_us_gov_affils')

In [42]:
df_aff

,doi,work_type_id,repository_code,source_title_id,source_type_id,pub_year,version,volume,issue,page_begin,...,created,last_updated,titles,descriptions,has_us_contributor,has_us_creator,has_us_publisher,has_us_repository,us_affils,n_banned_terms
0,10.60692/eahyw-7cs29,27,iapx.bsycxq,NaN,NaN,2019,v1,NaN,NaN,NaN,...,2024-07-16 10:09:02,2024-07-16 10:09:03,The power of partners: positively engaging net...,Journal of the International AIDS SocietyVolum...,0,1,0,0,1,1344
1,10.60692/7n7t0-t4212,27,iapx.bsycxq,NaN,NaN,2019,v1,NaN,NaN,NaN,...,2024-07-16 10:09:02,2024-07-16 10:09:03,The power of partners: positively engaging net...,Journal of the International AIDS SocietyVolum...,0,1,0,0,1,1344
2,10.60692/j3ayf-s0b37,27,iapx.bsycxq,NaN,NaN,2020,v1,NaN,NaN,NaN,...,2024-06-19 09:28:46,2024-06-22 13:17:23,Involvement of African men and transgender wom...,"In sub-Saharan Africa, men who have sex with m...",0,1,0,0,1,1261
3,10.60692/81xzq-njj11,27,iapx.bsycxq,NaN,NaN,2020,v1,NaN,NaN,NaN,...,2024-06-19 09:28:46,2024-06-22 13:17:23,Involvement of African men and transgender wom...,"In sub-Saharan Africa, men who have sex with m...",0,1,0,0,1,1261
4,10.60692/qynam-jwr27,27,iapx.bsycxq,NaN,NaN,2021,v1,NaN,NaN,NaN,...,2024-06-19 10:12:49,2024-06-22 13:26:05,"Response to: ""Inclusion as Illusion: Erasing T...",We appreciate the letter in response to the re...,0,1,0,0,1,858
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15304,10.6084/m9.figshare.c.7259322,4,figshare.ars,NaN,NaN,2024,NaN,NaN,NaN,NaN,...,2024-08-18 19:56:45,2024-08-18 19:56:46,The Retrospective Stressor Analysis (RSA): a n...,Abstract Background Resident physicians are at...,0,1,0,0,1,1
15305,10.6084/m9.figshare.c.6914706.v1,4,figshare.ars,NaN,NaN,2023,NaN,NaN,NaN,NaN,...,2023-11-05 04:20:24,2023-11-05 04:20:25,Identification of transcriptionally active tra...,Abstract Background The genomes of many major ...,0,1,0,0,1,1
15306,10.6084/m9.figshare.c.6842752,4,figshare.ars,NaN,NaN,2024,NaN,NaN,NaN,NaN,...,2024-08-14 00:18:19,2024-08-14 00:18:21,Urban malaria vector bionomics and human sleep...,Abstract Background Malaria is endemic in Sene...,0,1,0,0,1,1
15307,10.6084/m9.figshare.c.6889622.v1,4,figshare.ars,NaN,NaN,2023,NaN,NaN,NaN,NaN,...,2023-10-20 03:42:22,2024-08-16 09:47:22,Hepatozoon spp. infection in wild canids in th...,Abstract Background Hepatozoon spp. are apicom...,0,1,0,0,1,1
15308,10.7799/2425969,9,doe.nrel,NaN,NaN,2024,NaN,NaN,NaN,NaN,...,2024-08-03 02:18:50,2024-08-03 02:18:50,Reference Site Condition Datasets for Floating...,Floating offshore wind farm design is highly s...,0,0,0,1,1,1

In [24]:
df_drp = pd.read_csv('00_data/drp_withdoi.csv')

Check DRP data vs df_us_aff

In [ ]:
df_comp = add_flagged_column(df_comp, abstract_col='descriptions', title_col='titles')
df_aff = add_flagged_column(df_aff, abstract_col='descriptions', title_col='titles')

In [43]:
df_aff = add_flagged_column(df_aff, abstract_col='descriptions', title_col='titles')

In [44]:
df_aff.to_csv('00_data/df_aff.csv')
df_comp.to_csv('00_data/df_comp.csv')

In [26]:
df_comp["label"] = 0
df_drp['label'] = 1

In [27]:
df_drp.describe()

,Unnamed: 0.1,Unnamed: 0,resource_count,id,size,project_id,dc_status,dc_prefix,dc_publicationYear,dc_metadataVersion,...,num_flagged_words_title,num_pen_words_title,num_nyt_words_title,n_banned_terms_title,num_flagged_words_total,num_pen_words_total,num_nyt_words_total,n_banned_terms_total,has_flagged_word_total,label
count,2539.00000,2539.000000,2539.000000,2539.000000,2227.000000,2416.000000,2539.0,2539.000000,2539.000000,2539.000000,...,2539.000000,2539.000000,2539.000000,2539.000000,2539.000000,2539.000000,2539.000000,2539.000000,2539.000000,2539.0
mean,1269.00000,1328.963371,1.051989,1635.188657,2.361243,235798.617550,200.0,10.398657,2025.307995,0.052383,...,0.253643,0.247341,0.109098,0.358015,1.167389,1.064199,0.643167,3.059866,0.464750,1.0
std,733.09049,801.694600,0.304379,850.436635,39.234400,11317.988498,0.0,0.059128,1.105390,0.700679,...,0.664492,0.653737,0.443311,1.037433,1.714889,1.655582,1.207526,12.653983,0.498854,0.0
min,0.00000,0.000000,1.000000,0.000000,0.000000,100448.000000,200.0,10.220020,1980.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0
25%,634.50000,635.500000,1.000000,954.500000,0.000000,228159.250000,200.0,10.388600,2025.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0
50%,1269.00000,1270.000000,1.000000,1678.000000,0.000800,239974.500000,200.0,10.388600,2025.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0
75%,1903.50000,2074.500000,1.000000,2366.500000,0.028950,243424.250000,200.0,10.388600,2026.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,1.000000,3.000000,1.000000,1.0
max,2538.00000,2712.000000,5.000000,3022.000000,1300.000000,244901.000000,200.0,10.791000,2026.000000,29.000000,...,5.000000,5.000000,4.000000,9.000000,11.000000,10.000000,9.000000,500.000000,1.000000,1.0

wanted to match by year but still hasnt solved the missing og year problem in drp - hence random downsampling for testing

In [28]:
import pandas as pd

# assume df_drp and df_comp already loaded

df_comp_sample = df_comp.sample(
    n=len(df_drp),
    random_state=42
)

df_balanced = pd.concat([df_drp, df_comp_sample], ignore_index=True)

print(df_balanced["label"].value_counts())

label
1    2539
0    2539
Name: count, dtype: int64

In [29]:
df_balanced.groupby("label")["n_banned_terms_total"].mean()

label
0    6.261126
1    3.059866
Name: n_banned_terms_total, dtype: float64

In [ ]:
df_drp.groupby("label")["has_flagged_word_total"].mean()

label
1    0.46475
Name: has_flagged_word_total, dtype: float64

In [ ]:
drp_rate = df_drp["has_flagged_word_total"].mean()

comp_with = df_comp[df_comp["has_flagged_word_total"] == 1]
comp_without = df_comp[df_comp["has_flagged_word_total"] == 0]

n_without = len(comp_without)

target_n = len(df_drp)
n_with = min(len(comp_with), target_n - n_without)

comp_balanced = pd.concat([
    comp_with.sample(n=n_with, random_state=42),
    comp_without
], ignore_index=True)

print(comp_balanced["has_flagged_word_total"].value_counts())
print(comp_balanced.shape)

has_flagged_word_total
1    2328
0     211
Name: count, dtype: int64
(2539, 48)

In [ ]:
comp_with = df_comp[df_comp["has_flagged_word_total"] == 1]
comp_without = df_comp[df_comp["has_flagged_word_total"] == 0]

n_without = len(comp_without)
n_with = n_without

comp_balanced = pd.concat([
    comp_with.sample(n=n_with, random_state=42),
    comp_without.sample(n=n_without, random_state=42)
], ignore_index=True)

print(comp_balanced["has_flagged_word_total"].mean())
print(comp_balanced.shape)

0.5
(422, 48)

In [37]:
print("DRP size:", len(df_drp))
print("Comparator size:", len(df_comp))
print("Comparator with flagged:", len(comp_with))
print("Comparator without flagged:", len(comp_without))

DRP size: 2539
Comparator size: 15447
Comparator with flagged: 15236
Comparator without flagged: 211

df_us_aff vs df_not_gov

In [38]:
df_comp

,doi,work_type_id,repository_code,source_title_id,source_type_id,pub_year,version,volume,issue,page_begin,...,num_flagged_words_title,num_pen_words_title,num_nyt_words_title,n_banned_terms_title,num_flagged_words_total,num_pen_words_total,num_nyt_words_total,n_banned_terms_total,has_flagged_word_total,label
0,10.11575/prism/21016,17.0,ucalg.library,NaN,NaN,2004.0,NaN,NaN,NaN,NaN,...,4,4,4,14,5,5,5,16,1,0
1,10.11575/prism/1068,17.0,ucalg.library,NaN,NaN,2007.0,NaN,NaN,NaN,NaN,...,3,3,3,8,3,3,3,8,1,0
2,10.11575/jet.v39i1.52626,27.0,ucalg.library,28841.0,5.0,2018.0,NaN,NaN,NaN,Vol 39 No 1 (2005),...,2,2,2,6,3,3,3,8,1,0
3,10.11575/prism/11938,17.0,ucalg.library,NaN,NaN,2003.0,NaN,NaN,NaN,NaN,...,0,0,0,0,2,2,1,3,1,0
4,10.11575/jet.v22i3.44234,27.0,ucalg.library,28841.0,5.0,2018.0,NaN,NaN,NaN,Vol 22 No 3 (1988),...,3,2,3,6,3,2,3,6,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15442,10.4229/27theupvsec2012-2av.4.2,27.0,tib.wip,4280.0,5.0,2012.0,NaN,NaN,NaN,NaN,...,3,3,1,6,4,4,2,8,1,0
15443,10.4229/27theupvsec2012-2av.4.51,27.0,tib.wip,3257.0,5.0,2012.0,NaN,NaN,NaN,NaN,...,3,3,1,5,3,3,1,5,1,0
15444,10.4230/oasics.slate.2012.185,6.0,lzi.drops,NaN,NaN,2012.0,NaN,NaN,NaN,NaN,...,1,1,1,2,1,1,1,2,1,0
15445,10.17615/jvmj-jx46,27.0,gdcc.odum-library,NaN,NaN,2024.0,NaN,NaN,NaN,NaN,...,1,1,1,2,1,1,1,2,1,0
15446,10.4232/1.0200,9.0,gesis.gesis,NaN,NaN,1966.0,1.0.0,NaN,NaN,NaN,...,3,3,3,6,3,3,3,6,1,0

In [39]:
df_aff

,doi,work_type_id,repository_code,source_title_id,source_type_id,pub_year,version,volume,issue,page_begin,...,has_flagged_word_title,num_flagged_words_title,num_pen_words_title,num_nyt_words_title,n_banned_terms_title,num_flagged_words_total,num_pen_words_total,num_nyt_words_total,n_banned_terms_total,has_flagged_word_total
0,10.11575/prism/21016,17.0,ucalg.library,NaN,NaN,2004.0,NaN,NaN,NaN,NaN,...,1,4,4,4,14,5,5,5,16,1
1,10.11575/prism/1068,17.0,ucalg.library,NaN,NaN,2007.0,NaN,NaN,NaN,NaN,...,1,3,3,3,8,3,3,3,8,1
2,10.11575/jet.v39i1.52626,27.0,ucalg.library,28841.0,5.0,2018.0,NaN,NaN,NaN,Vol 39 No 1 (2005),...,1,2,2,2,6,3,3,3,8,1
3,10.11575/prism/11938,17.0,ucalg.library,NaN,NaN,2003.0,NaN,NaN,NaN,NaN,...,0,0,0,0,0,2,2,1,3,1
4,10.11575/jet.v22i3.44234,27.0,ucalg.library,28841.0,5.0,2018.0,NaN,NaN,NaN,Vol 22 No 3 (1988),...,1,3,2,3,6,3,2,3,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15442,10.4229/27theupvsec2012-2av.4.2,27.0,tib.wip,4280.0,5.0,2012.0,NaN,NaN,NaN,NaN,...,1,3,3,1,6,4,4,2,8,1
15443,10.4229/27theupvsec2012-2av.4.51,27.0,tib.wip,3257.0,5.0,2012.0,NaN,NaN,NaN,NaN,...,1,3,3,1,5,3,3,1,5,1
15444,10.4230/oasics.slate.2012.185,6.0,lzi.drops,NaN,NaN,2012.0,NaN,NaN,NaN,NaN,...,1,1,1,1,2,1,1,1,2,1
15445,10.17615/jvmj-jx46,27.0,gdcc.odum-library,NaN,NaN,2024.0,NaN,NaN,NaN,NaN,...,1,1,1,1,2,1,1,1,2,1
15446,10.4232/1.0200,9.0,gesis.gesis,NaN,NaN,1966.0,1.0.0,NaN,NaN,NaN,...,1,3,3,3,6,3,3,3,6,1